org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

## Environment
# https://projects.neoforged.net/neoforged/neoforge
minecraft_version=26.2
minecraft_version_range=[26.2]
neo_version=26.2.0.88

## Optional integrations
# https://maven.blamejared.com/mezz/jei/
jei_version=30.39.0.232

## Mod
mod_id=ezstorage
mod_name=Simple Storage
mod_license=MIT
mod_version=2.0.0-alpha.1
mod_group_id=com.zerofall.ezstorage
mod_authors=zerofall, Pilzinsel64, LITW-Refined contributors
mod_description=An early-game storage system that scales and evolves as you progress, while keeping the vanilla flair.
